### ISSUE TITLE
It might to good thing add syllable like ligatures.

### ISSUE THREAD

**Issue by rovasiras** [notofonts/old-hungarian#17]
It might to good thing add syllable like ligatures. (consoant + vowel)
It increase the quality. Several of them are single words, too: l+ó= ló in English ",horse"

**Comment by rovasiras** [comment]
@simoncozens This is a good idea, but there is no Unicode document that requires it. I close it.

**Comment by rovasiras** [comment]
@simoncozens Is it alloved to add ligatures which aren't in the Unicode docs but useful?
I mean the consonant + vowel syllables. 
Some of these ligatures are already in the font.

**Comment by kovacshviktor** [comment]
@simoncozens I discussed the topic of syllabic ligatures with an Old Hungarian scribe (András Tisza) and a font development expert.
He told me two things: either all syllabic ligatures should be put into a font, or none at all.
The other: vowel + consonant syllable marks should be taken out of discrete ligatures because if they are not under control, they make the spelling confusing and unreadable.

My own opinion is that consonant + consonant ligatures should be excluded from the discrete ligatures, because they are rarely used and it is not possible to judge in advance whether they might cause readability problems.

The ligatures K+V, V+V, K+SZ, J+I should only be used with ZWJ, because they are used as the letters Q, W, X and Y.

**Comment by kovacshviktor** [comment]
@simoncozens I will not add additional ligatures.
I follow the standard, as it possible. I will not add accents, because of that it was used by only 2-3 person in their correspondence in, they used "triangle o", "Y shaped b", these forms aren't historical, and these have not been correctly recorded in the Unicode standard.

**Comment by rovasiras** [comment]
@simoncozens I close it.
